version: "3"
services:
  server:
    build: ./server
    container_name: todos-server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${CLIENT_PORT}:${CLIENT_PORT}

  client:
    depends_on:
      - server
    build: ./client
    container_name: todos-client
    network_mode: service:server
    env_file:
      - .env
