version: "3"
services:
  server:
    build: ./server
    container_name: todos-server
    volumes:
      - ./server/database:/usr/src/app/database
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-4000}:${SERVER_PORT:-4000}
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}

  client:
    depends_on:
      - server
    build: ./client
    container_name: todos-client
    network_mode: service:server
    env_file:
      - .env
